export type Teacher = {
  id: string; name: string; initials: string; bg: string; color: string;
  photo?: string;
  serviceNo: string; subject: string; grade: string;
  school: string; district: string; type: string;
  gender: string; phone: string; status: string; exp: number;
  // Personal
  nic: string; dob: string; religion: string; ethnicity: string;
  nationality: string; maritalStatus: string;
  // Contact
  email: string; permanentAddress: string; currentAddress: string;
  emergencyContactName: string; emergencyContactPhone: string;
  // Professional
  firstAppointmentDate: string; currentSchoolDate: string;
  employmentType: string; serviceCategory: string; salaryGrade: string;
  gradesTaught: string; medium: string; classTeacher: string; additionalRoles: string;
  // Academic
  highestQual: string; degrees: string; teachingQual: string; otherCerts: string;
  // Previous
  previousSchools: string; transferHistory: string; transferReason: string;
  // Health
  bloodGroup: string; medicalConditions: string; disabilityStatus: string;
  // Account
  loginEmail: string; roleLevel: string;
};

export const TEACHERS: Teacher[] = [
  {
    id:'T001', name:'Mrs. Kumari Perera', initials:'KP', bg:'bg-blue-100', color:'text-blue-700',
    serviceNo:'MOE-T-2008-12345', subject:'Mathematics', grade:'Secondary (G6–11)',
    school:'Kalutara Vidyalaya', district:'Kalutara', type:'Government',
    gender:'Female', phone:'+94 77 123 4567', status:'Active', exp:15,
    nic:'198556204520V', dob:'1985-08-22', religion:'Buddhism', ethnicity:'Sinhalese',
    nationality:'Sri Lankan', maritalStatus:'Married',
    email:'k.perera@kvl.edu.lk', permanentAddress:'45/A, Galle Road, Kalutara South, Kalutara 12000',
    currentAddress:'', emergencyContactName:'Mr. D. Perera', emergencyContactPhone:'+94 77 123 4568',
    firstAppointmentDate:'2009-03-15', currentSchoolDate:'2015-01-10',
    employmentType:'Permanent', serviceCategory:'SLTS Grade II', salaryGrade:'MN-1, Step 7',
    gradesTaught:'Grades 6–11', medium:'Sinhala', classTeacher:'Grade 9A',
    additionalRoles:'Head of Mathematics Department',
    highestQual:"Bachelor's Degree", degrees:"B.Sc. Mathematics – University of Kelaniya (2nd Class Lower)",
    teachingQual:'Diploma in Education – NIE, 2010', otherCerts:'Cambridge ICT Starters (2019)',
    previousSchools:'Beruwala Central College, Kalutara Zone (2009–2015)',
    transferHistory:'Transferred from Beruwala Central College on teacher request (2015)',
    transferReason:'Request transfer – proximity to residence',
    bloodGroup:'B+', medicalConditions:'None', disabilityStatus:'None',
    loginEmail:'k.perera@iskole.lk', roleLevel:'Teacher',
  },
  {
    id:'T002', name:'Mr. Nimal Dissanayake', initials:'ND', bg:'bg-emerald-100', color:'text-emerald-700',
    serviceNo:'MOE-T-2015-23456', subject:'Science', grade:'Primary (G1–5)',
    school:'Colombo Central School', district:'Colombo', type:'Government',
    gender:'Male', phone:'+94 71 234 5678', status:'Active', exp:8,
    nic:'199012304567V', dob:'1990-04-12', religion:'Buddhism', ethnicity:'Sinhalese',
    nationality:'Sri Lankan', maritalStatus:'Single',
    email:'n.dissanayake@ccs.edu.lk', permanentAddress:'12, Temple Road, Nugegoda, Colombo 10250',
    currentAddress:'22/3, Baseline Road, Borella, Colombo 00800',
    emergencyContactName:'Mrs. S. Dissanayake', emergencyContactPhone:'+94 71 234 5679',
    firstAppointmentDate:'2016-08-01', currentSchoolDate:'2016-08-01',
    employmentType:'Permanent', serviceCategory:'SLTS Grade III', salaryGrade:'MN-1, Step 4',
    gradesTaught:'Grades 1–5', medium:'Sinhala', classTeacher:'Grade 3B',
    additionalRoles:'Science Club Coordinator',
    highestQual:"Bachelor's Degree", degrees:"B.Sc. (General) – University of Sri Jayewardenepura (2nd Class Upper)",
    teachingQual:'Postgraduate Diploma in Education – NIE, 2016', otherCerts:'',
    previousSchools:'None – first appointment at current school',
    transferHistory:'N/A', transferReason:'N/A',
    bloodGroup:'O+', medicalConditions:'None', disabilityStatus:'None',
    loginEmail:'n.dissanayake@iskole.lk', roleLevel:'Teacher',
  },
  {
    id:'T003', name:'Ms. Priya Subramaniam', initials:'PS', bg:'bg-violet-100', color:'text-violet-700',
    serviceNo:'MOE-T-2019-34567', subject:'Tamil', grade:'A/L (G12–13)',
    school:'Jaffna Model School', district:'Jaffna', type:'Government',
    gender:'Female', phone:'+94 76 345 6789', status:'Active', exp:4,
    nic:'199778901234V', dob:'1997-11-03', religion:'Hinduism', ethnicity:'Sri Lanka Tamil',
    nationality:'Sri Lankan', maritalStatus:'Single',
    email:'p.subramaniam@jms.edu.lk', permanentAddress:'78, Nallur Road, Jaffna 40000',
    currentAddress:'', emergencyContactName:'Mr. R. Subramaniam', emergencyContactPhone:'+94 76 345 6790',
    firstAppointmentDate:'2020-01-06', currentSchoolDate:'2020-01-06',
    employmentType:'Permanent', serviceCategory:'SLTS Grade III', salaryGrade:'MN-1, Step 2',
    gradesTaught:'Grades 12–13', medium:'Tamil', classTeacher:'',
    additionalRoles:'Tamil Literary Association Coordinator',
    highestQual:"Bachelor's Degree", degrees:'B.A. Tamil – University of Jaffna (1st Class Hons.)',
    teachingQual:'Postgraduate Diploma in Education – NIE, 2019', otherCerts:'',
    previousSchools:'None – first appointment', transferHistory:'N/A', transferReason:'N/A',
    bloodGroup:'A+', medicalConditions:'None', disabilityStatus:'None',
    loginEmail:'p.subramaniam@iskole.lk', roleLevel:'Teacher',
  },
  {
    id:'T004', name:'Mr. Ruwan Silva', initials:'RS', bg:'bg-amber-100', color:'text-amber-700',
    serviceNo:'MOE-T-2012-45678', subject:'History', grade:'Secondary (G6–11)',
    school:'Kandy Heritage School', district:'Kandy', type:'Semi-Government',
    gender:'Male', phone:'+94 78 456 7890', status:'On Leave', exp:11,
    nic:'198634501234V', dob:'1986-06-20', religion:'Buddhism', ethnicity:'Sinhalese',
    nationality:'Sri Lankan', maritalStatus:'Married',
    email:'r.silva@khs.edu.lk', permanentAddress:'33, Peradeniya Road, Kandy 20000',
    currentAddress:'', emergencyContactName:'Mrs. A. Silva', emergencyContactPhone:'+94 78 456 7891',
    firstAppointmentDate:'2013-04-01', currentSchoolDate:'2018-09-01',
    employmentType:'Permanent', serviceCategory:'SLTS Grade II', salaryGrade:'MN-1, Step 5',
    gradesTaught:'Grades 6–11', medium:'Sinhala', classTeacher:'Grade 10C',
    additionalRoles:'History Society Patron, Sectional Head (Humanities)',
    highestQual:"Bachelor's Degree", degrees:'B.A. History – University of Peradeniya (2nd Class Upper)',
    teachingQual:'Diploma in Education – NIE, 2013', otherCerts:'',
    previousSchools:'Katugastota National School, Kandy Zone (2013–2018)',
    transferHistory:'Transferred to Kandy Heritage School (2018)', transferReason:'Promotion to Senior Post',
    bloodGroup:'AB+', medicalConditions:'None', disabilityStatus:'None',
    loginEmail:'r.silva@iskole.lk', roleLevel:'Head of Department',
  },
  {
    id:'T005', name:'Mrs. Fathima Nazreen', initials:'FN', bg:'bg-rose-100', color:'text-rose-700',
    serviceNo:'MOE-T-2017-56789', subject:'English', grade:'Secondary (G6–11)',
    school:'Colombo Central School', district:'Colombo', type:'Government',
    gender:'Female', phone:'+94 72 567 8901', status:'Active', exp:6,
    nic:'199012601234V', dob:'1990-02-14', religion:'Islam', ethnicity:'Sri Lanka Moor',
    nationality:'Sri Lankan', maritalStatus:'Married',
    email:'f.nazreen@ccs.edu.lk', permanentAddress:'55, Station Road, Dehiwala, Colombo 10350',
    currentAddress:'', emergencyContactName:'Mr. M. Nazreen', emergencyContactPhone:'+94 72 567 8902',
    firstAppointmentDate:'2018-01-15', currentSchoolDate:'2018-01-15',
    employmentType:'Permanent', serviceCategory:'SLTS Grade III', salaryGrade:'MN-1, Step 3',
    gradesTaught:'Grades 6–11', medium:'English', classTeacher:'Grade 8A',
    additionalRoles:'English Literary Society Coordinator, Debate Club Coach',
    highestQual:"Bachelor's Degree", degrees:'B.A. English – University of Colombo (2nd Class Upper)',
    teachingQual:'Postgraduate Diploma in Education – NIE, 2017', otherCerts:'CELTA – British Council (2019)',
    previousSchools:'None – first appointment', transferHistory:'N/A', transferReason:'N/A',
    bloodGroup:'O–', medicalConditions:'None', disabilityStatus:'None',
    loginEmail:'f.nazreen@iskole.lk', roleLevel:'Teacher',
  },
  {
    id:'T006', name:'Mr. Kamal Fernando', initials:'KF', bg:'bg-cyan-100', color:'text-cyan-700',
    serviceNo:'N/A', subject:'Physical Ed.', grade:'All Levels',
    school:'Galle International Academy', district:'Galle', type:'Private',
    gender:'Male', phone:'+94 70 678 9012', status:'Active', exp:18,
    nic:'197845601234V', dob:'1978-09-05', religion:'Christianity', ethnicity:'Sinhalese',
    nationality:'Sri Lankan', maritalStatus:'Married',
    email:'k.fernando@gia.edu.lk', permanentAddress:'10, Marine Drive, Galle 80000',
    currentAddress:'', emergencyContactName:'Mrs. L. Fernando', emergencyContactPhone:'+94 70 678 9013',
    firstAppointmentDate:'2006-04-01', currentSchoolDate:'2010-01-05',
    employmentType:'Permanent', serviceCategory:'Private School Staff', salaryGrade:'PS-3, Step 9',
    gradesTaught:'Grades 1–13', medium:'English', classTeacher:'',
    additionalRoles:'Sports Director, Cricket Coach, Athletics Coordinator',
    highestQual:"Bachelor's Degree", degrees:'B.Sc. Sports Science – University of Moratuwa (2nd Class Lower)',
    teachingQual:'Diploma in Physical Education – NISI, 2007', otherCerts:'Cricket Coaching Level 2 – SLC (2015)',
    previousSchools:'Richmond College, Galle (2006–2010)',
    transferHistory:'Moved to Galle International Academy for private sector opportunity (2010)',
    transferReason:'Better remuneration and facilities',
    bloodGroup:'A–', medicalConditions:'None', disabilityStatus:'None',
    loginEmail:'k.fernando@iskole.lk', roleLevel:'Teacher',
  },
  {
    id:'T007', name:'Mrs. Sandamali Rajapaksha', initials:'SR', bg:'bg-indigo-100', color:'text-indigo-700',
    serviceNo:'MOE-T-2010-78901', subject:'Sinhala', grade:'Primary (G1–5)',
    school:'Kalutara Vidyalaya', district:'Kalutara', type:'Government',
    gender:'Female', phone:'+94 77 789 0123', status:'Active', exp:13,
    nic:'198367801234V', dob:'1983-04-17', religion:'Buddhism', ethnicity:'Sinhalese',
    nationality:'Sri Lankan', maritalStatus:'Married',
    email:'s.rajapaksha@kvl.edu.lk', permanentAddress:'22, School Lane, Beruwala, Kalutara 12070',
    currentAddress:'', emergencyContactName:'Mr. T. Rajapaksha', emergencyContactPhone:'+94 77 789 0124',
    firstAppointmentDate:'2011-03-01', currentSchoolDate:'2011-03-01',
    employmentType:'Permanent', serviceCategory:'SLTS Grade II', salaryGrade:'MN-1, Step 6',
    gradesTaught:'Grades 1–5', medium:'Sinhala', classTeacher:'Grade 4A',
    additionalRoles:'Sinhala Drama Society Patron',
    highestQual:"Bachelor's Degree", degrees:'B.A. Sinhala – University of Kelaniya (2nd Class Upper)',
    teachingQual:'Diploma in Education – NIE, 2011', otherCerts:'',
    previousSchools:'None – first appointment', transferHistory:'N/A', transferReason:'N/A',
    bloodGroup:'B–', medicalConditions:'None', disabilityStatus:'None',
    loginEmail:'s.rajapaksha@iskole.lk', roleLevel:'Teacher',
  },
  {
    id:'T008', name:'Mr. Balakrishnan T.', initials:'BT', bg:'bg-teal-100', color:'text-teal-700',
    serviceNo:'MOE-T-2014-89012', subject:'Mathematics', grade:'A/L (G12–13)',
    school:'Jaffna Model School', district:'Jaffna', type:'Government',
    gender:'Male', phone:'+94 76 890 1234', status:'Active', exp:9,
    nic:'198912301234V', dob:'1989-05-30', religion:'Hinduism', ethnicity:'Sri Lanka Tamil',
    nationality:'Sri Lankan', maritalStatus:'Single',
    email:'b.thayalan@jms.edu.lk', permanentAddress:'14, Hospital Road, Jaffna 40000',
    currentAddress:'', emergencyContactName:'Mr. V. Thayalan', emergencyContactPhone:'+94 76 890 1235',
    firstAppointmentDate:'2015-08-15', currentSchoolDate:'2015-08-15',
    employmentType:'Permanent', serviceCategory:'SLTS Grade III', salaryGrade:'MN-1, Step 4',
    gradesTaught:'Grades 12–13', medium:'Tamil', classTeacher:'',
    additionalRoles:'Mathematics Olympiad Coordinator',
    highestQual:"Bachelor's Degree", degrees:'B.Sc. Mathematics – University of Jaffna (1st Class Hons.)',
    teachingQual:'Postgraduate Diploma in Education – NIE, 2015', otherCerts:'',
    previousSchools:'None – first appointment', transferHistory:'N/A', transferReason:'N/A',
    bloodGroup:'O+', medicalConditions:'None', disabilityStatus:'None',
    loginEmail:'b.thayalan@iskole.lk', roleLevel:'Teacher',
  },
  {
    id:'T009', name:'Ms. Dilini Wickramasinghe', initials:'DW', bg:'bg-pink-100', color:'text-pink-700',
    serviceNo:'MOE-T-2020-90123', subject:'ICT', grade:'Secondary (G6–11)',
    school:'Kandy Heritage School', district:'Kandy', type:'Semi-Government',
    gender:'Female', phone:'+94 71 901 2345', status:'Active', exp:3,
    nic:'200012301234V', dob:'2000-03-08', religion:'Buddhism', ethnicity:'Sinhalese',
    nationality:'Sri Lankan', maritalStatus:'Single',
    email:'d.wickramasinghe@khs.edu.lk', permanentAddress:'67, Dharmaraja Road, Kandy 20000',
    currentAddress:'', emergencyContactName:'Mrs. P. Wickramasinghe', emergencyContactPhone:'+94 71 901 2346',
    firstAppointmentDate:'2021-02-01', currentSchoolDate:'2021-02-01',
    employmentType:'Graduate Trainee', serviceCategory:'SLTS Grade III (Probationary)', salaryGrade:'MN-1, Step 1',
    gradesTaught:'Grades 6–11', medium:'Sinhala', classTeacher:'',
    additionalRoles:'Robotics Club Co-coordinator',
    highestQual:"Bachelor's Degree", degrees:'B.Sc. Information Technology – University of Moratuwa (2nd Class Upper)',
    teachingQual:'Postgraduate Diploma in Education – NIE, 2020', otherCerts:'Google Certified Educator Level 1 (2022)',
    previousSchools:'None – first appointment', transferHistory:'N/A', transferReason:'N/A',
    bloodGroup:'A+', medicalConditions:'None', disabilityStatus:'None',
    loginEmail:'d.wickramasinghe@iskole.lk', roleLevel:'Teacher',
  },
  {
    id:'T010', name:'Mr. Saman Jayakody', initials:'SJ', bg:'bg-orange-100', color:'text-orange-700',
    serviceNo:'MOE-T-2006-01234', subject:'Commerce', grade:'Secondary (G6–11)',
    school:'Galle International Academy', district:'Galle', type:'Private',
    gender:'Male', phone:'+94 77 012 3456', status:'Active', exp:17,
    nic:'197934501234V', dob:'1979-12-22', religion:'Buddhism', ethnicity:'Sinhalese',
    nationality:'Sri Lankan', maritalStatus:'Married',
    email:'s.jayakody@gia.edu.lk', permanentAddress:'5, Marine Street, Unawatuna, Galle 80600',
    currentAddress:'', emergencyContactName:'Mrs. K. Jayakody', emergencyContactPhone:'+94 77 012 3457',
    firstAppointmentDate:'2007-01-10', currentSchoolDate:'2014-06-01',
    employmentType:'Permanent', serviceCategory:'Private School Staff', salaryGrade:'PS-3, Step 8',
    gradesTaught:'Grades 6–11', medium:'English', classTeacher:'Grade 11B',
    additionalRoles:'Commerce Club Patron, Young Entrepreneurs Coordinator',
    highestQual:"Master's Degree", degrees:"M.B.A. – University of Sri Jayewardenepura (2016); B.B.Mgt. – University of Kelaniya (2003)",
    teachingQual:'Diploma in Education – NIE, 2007', otherCerts:'CIMA Certificate Level (2010)',
    previousSchools:'Mahinda College, Galle (2007–2014)',
    transferHistory:'Moved to Galle International Academy (2014)', transferReason:'Private sector career growth',
    bloodGroup:'B+', medicalConditions:'Type 2 Diabetes (managed)', disabilityStatus:'None',
    loginEmail:'s.jayakody@iskole.lk', roleLevel:'Teacher',
  },
  {
    id:'T011', name:'Mrs. Chandra Gunawardena', initials:'CG', bg:'bg-lime-100', color:'text-lime-700',
    serviceNo:'MOE-T-2011-11235', subject:'Biology', grade:'A/L (G12–13)',
    school:'Colombo Central School', district:'Colombo', type:'Government',
    gender:'Female', phone:'+94 72 123 5678', status:'Active', exp:12,
    nic:'198423401234V', dob:'1984-08-11', religion:'Buddhism', ethnicity:'Sinhalese',
    nationality:'Sri Lankan', maritalStatus:'Married',
    email:'c.gunawardena@ccs.edu.lk', permanentAddress:'88, Horana Road, Panadura, Colombo 12500',
    currentAddress:'', emergencyContactName:'Mr. P. Gunawardena', emergencyContactPhone:'+94 72 123 5679',
    firstAppointmentDate:'2012-03-01', currentSchoolDate:'2019-01-01',
    employmentType:'Permanent', serviceCategory:'SLTS Grade II', salaryGrade:'MN-1, Step 6',
    gradesTaught:'Grades 12–13', medium:'English', classTeacher:'',
    additionalRoles:'Science Society Patron, Biology Laboratory Coordinator',
    highestQual:"Master's Degree", degrees:"M.Sc. Molecular Biology – University of Colombo (2017); B.Sc. Biology – University of Colombo (2007)",
    teachingQual:'Postgraduate Diploma in Education – NIE, 2012', otherCerts:'',
    previousSchools:'Panadura Balika Vidyalaya (2012–2019)',
    transferHistory:'Transferred to Colombo Central School (2019)', transferReason:'Post upgrade and career advancement',
    bloodGroup:'O+', medicalConditions:'None', disabilityStatus:'None',
    loginEmail:'c.gunawardena@iskole.lk', roleLevel:'Teacher',
  },
  {
    id:'T012', name:'Mr. Anura Bandara', initials:'AB', bg:'bg-purple-100', color:'text-purple-700',
    serviceNo:'MOE-T-2013-22346', subject:'Geography', grade:'Secondary (G6–11)',
    school:'Kalutara Vidyalaya', district:'Kalutara', type:'Government',
    gender:'Male', phone:'+94 71 234 6789', status:'Retired', exp:20,
    nic:'196745601234V', dob:'1967-09-14', religion:'Buddhism', ethnicity:'Sinhalese',
    nationality:'Sri Lankan', maritalStatus:'Married',
    email:'a.bandara@kvl.edu.lk', permanentAddress:'33, Kalutara North, Kalutara 12000',
    currentAddress:'', emergencyContactName:'Mrs. N. Bandara', emergencyContactPhone:'+94 71 234 6790',
    firstAppointmentDate:'2004-06-01', currentSchoolDate:'2004-06-01',
    employmentType:'Permanent', serviceCategory:'SLTS Grade I', salaryGrade:'MN-2, Step 10',
    gradesTaught:'Grades 6–11', medium:'Sinhala', classTeacher:'',
    additionalRoles:'Geography Society Patron, Retired – final year of service',
    highestQual:"Bachelor's Degree", degrees:'B.A. Geography – University of Colombo (2nd Class Upper)',
    teachingQual:'Diploma in Education – NIE, 2005', otherCerts:'',
    previousSchools:'Matugama Central College (2004–2010)',
    transferHistory:'Transferred to Kalutara Vidyalaya (2010)', transferReason:'Personal request',
    bloodGroup:'A–', medicalConditions:'Hypertension (managed)', disabilityStatus:'None',
    loginEmail:'a.bandara@iskole.lk', roleLevel:'Teacher',
  },
];
